:eqtable: %autowidth,frame=none,grid=none

= Category Theory
:sectnums:

== Definitions

[#def-category]
=== Definition Category

A *category* C consists of:

* A collection of objects, denoted by Obj~C~.
* A collection of morphisms (arrows) between objects, denoted by Mor~C~.
* A composition operation, denoted by ∘ : Mor~C~ × Mor~C~ → Mor~C~.
* For each object a in Obj~C~, an identity morphism id~a~ in Mor~C~.

The composition operation satisfies the following two axioms:

[lowerroman]
. (Associativity) For any morphisms f, g, and h in Mor~C~,  (f ∘ g) ∘ h = f ∘ (g ∘ h).
. (Identity) For any object a in Obj~C~ and any morphism f in Mor~C~,  f ∘ id~a~ = f and id~a~ ∘ f = f.


[#def-functor]
=== Definition Functor

Given two categories C and D, a *functor* F : C → D consists of:

* A function  F : Obj~C~ → Obj~D~
* A function  map~F~ : Mor~C~ → Mor~D~

These functions must satisfy the following two conditions:

[lowerroman]
. For any two morphisms f and g in Mor~C~,  map~F~ (f ∘ g) = map~F~ f ∘ map~F~ g.
. For any object a in Obj~C~,  map~F~ id~a~ = id~F a~.

If C and D are the same category, F is called an *endofunctor*.

[#def-product]
=== Definition Product and Coproduct
A *product* of two objects a and b is the object c equipped with two morphisms (called projections) p: c → a and q: c → b 
such that for any other object c' equipped with two projections p': c' → a and q': c' → b there is a unique morphism m: c' → c that factorizes those projections: 

[lowerroman]
. p' = p ∘ m
. q' = q ∘ m

Dually, a *coproduct* of two objects a and b is the object c equipped with two morphisms (called injections) i: a → c and j: b → c 
such that for any other object c' equipped with two injections i': a → c' and j': b → c' there is a unique morphism m: c → c' that factorizes those injections: 

[lowerroman]
. i' = m ∘ i
. j' = m ∘ j

== Examples

[#ex-fp]
=== The FP Category

The category *FP*, with objects being types and morphisms being functions, forms a category.

Composition of two functions f and g in Mor~FP~ is defined as  (f ∘ g) x = f (g x).

For any object a in Obj~FP~, id~a~ is defined as the function  id~a~ x = x.

_Proof._

To prove the equivalence of two functions, it suffices to show that they yield the same output for the same input.

[lowerroman]
. (Associativity) For any morphisms f, g, and h in Mor~FP~,  (f ∘ g) ∘ h = f ∘ (g ∘ h).

[{eqtable}] 
|===
| ((f ∘ g) ∘ h) x  | = (f ∘ g) (h x)   | (definition composition)
|                  | = f (g (h x))     | (definition composition)
|===

[lowerroman,start=2]
. (Identity) For any object a in Obj~FP~ and any morphism f in Mor~FP~,  f ∘ id~a~ = f and id~a~ ∘ f = f.

[{eqtable}] 
|===
| (f ∘ id~a~) x  |  = f (id~a~ x)   | (definition composition)
|                | = f x            | (definition id~a~)
|||
|(id~a~ ∘ f) x  |  = id~a~ (f x)    | (definition composition)
|               |  = f x            | (definition id~a~)
|===

∎

[#ex-List-functor]
=== The List Functor

The *List* type constructor forms an endofunctor in the category FP.

[{eqtable}]
|===
| List : Obj~T~ → Obj~T~                                |
| List a = Nil \| Cons a (List a)                       |
| map~List~ : Mor~T~ → Mor~T~                           | Or, specialized to FP,  map~List~ : (a → b) → (List a → List b)
| map~List~ f Nil = Nil                                 |
| map~List~ f (Cons x xs) = Cons (f x) (map~List~ f xs) |
|===

_Proof._

[lowerroman]
. For any two morphisms f and g in Mor~T~,  map~List~ (f ∘ g) = map~List~ f ∘ map~List~ g.

We prove that these two expressions are the same for all possible inputs, namely Nil and Cons x xs.

[{eqtable}]
|===
| map~List~ (f ∘ g) Nil            | = Nil                            |
|||
| (map~List~ f ∘ map~List~ g) Nil  | = map~List~ f (map~List~ g Nil)  | (definition composition)
|                                  | = map~List~ f Nil                | (definition map~List~)
|                                  | = Nil                            | (definition map~List~)
|===
  
[{eqtable}]
|===
| map~List~ (f ∘ g) (Cons x xs)           | = Cons ((f ∘ g) x) (map~List~ (f ∘ g) xs)            | (definition map~List~)
|||
| (map~List~ f ∘ map~List~ g) (Cons x xs) | = map~List~ f (map~List~ g (Cons x xs))              | (definition composition)
|                                         | = map~List~ f (Cons (g x) (map~List~ g xs))          | (definition map~List~)
|                                         | = Cons (f (g x)) (map~List~ f (map~List~ g xs))      | (definition map~List~)
|                                         | = Cons ((f ∘ g) x) ((map~List~ f ∘ map~List~ g) xs)  | (definition composition)
|===

All we have left to prove is that map~List~ (f ∘ g) xs = (map~List~ f ∘ map~List~ g) xs.
Because it is true for xs = Nil, it follows by induction that the statement is true for all xs.

[lowerroman,start=2]
. For any object a in Obj~T~,  map~List~ id~a~ = id~List a~. 

We prove that these two expressions are the same for all possible inputs, namely Nil and Cons x xs.

[{eqtable}]
|===
| map~List~ id~a~ Nil = Nil  | (definition map~List~)
||
| id~List a~ Nil = Nil       | (definition id~List a~)
|===

[{eqtable}]
|===
| map~List~ id~a~ (Cons x xs)  | = Cons (id~a~ x) (map~List~ id~a~ xs)  | (definition map~List~)
|                              | = Cons x (map~List~ id~a~ xs)          | (definition id~a~)
|||
| id~List a~ (Cons x xs)       | = Cons x xs                            | (definition id~List a~)
|===

All we have left to prove is that map~List~ id~a~ xs = xs.
Because it is true for xs = Nil, it follows by induction that the statement is true for all xs.

∎
