= Railroad Oriented Programming in C#: Part 1

link:/?page=rop-cs-2[Next part]

## The problem: implicit function failure

Functions are often designed for the *success path*: the return type only consists of the type the function will return in case of a successful execution.
The following function definition likely wouldn't stand out in an average code base.

[source,cs]
....
User GetUser(string username);
....

This function is supposed to return a User object for the user with the username that is passed into the function.
But sometimes the function isn't able to meet this expectation.

- maybe the user doesn't exist
- maybe because it needs to do a lookup in a datastore and the datastore is temporarily unreachable
- ...

If a function fails, usually one of the following things happens.

. A default value is returned, such as a null reference.
. An exception is thrown.


[pikchr]
....
include::rop.pikchr[]

X0: oval "username" fit
arrow
X1: box "GetUser" fit
arrow 
X2: oval "User" fill lightblue fit
down
arrow dashed from X1.s down
X3: oval "?" fill crimson fit
....

### Problems with using default values for failure
- For *value types* the default value is a valid member of the value space of the type. So there would be no way to distinguish between a success return value and a failure return value in this case.
- For *reference types* the default value (`null`) is not a valid member of the value space. The compiler however treats it as it _were_ a valid member, leading to null-reference bugs. Since the addition of nonnullable reference types in C# 8.0 this set of problems has been diminished a great deal, but a non-negligible pool of pitfalls remains.
- There is no way to return any data along with the failure, such as an error message or some object indicating the reason or nature of the failure.
- There is no way to distinguish between different kinds of failures.

### Problems with using exceptions for failure
- Exceptions are not part of the function signature. As such a caller of a function does not know which exceptions to catch unless he reads all the code that is possibly hit by the function, assuming that he even has access to it.
- In well-defined and well-maintained APIs the list of possible exceptions a function can throw is stated in the documentation. But the compiler is not aware of this. So:
  * The user of the API can easily overlook exceptions and get away without compiler warnings.
  * If the API changes over time and adds more exceptions, the user will not be notified of this by the compiler.
  * Most functions are not part of a well-defined API.

### The general problem of implicit failure paths
While the above paragraphs point out some problems with the respective failure-handling strategies, perhaps the biggest of all problems is this: the *failure path* of `GetUser` is *implicitly defined*.
It is not part of the function signature, and the compiler is not aware of it.
As such, it doesn't get the same amount of attention from the programmer as the success path and is, frankly, too often completely overlooked.

### Solution: explicit failure
The solution is pretty obvious: make the failure path part of the normal return type of the function.

[pikchr]
....
scale = 0.8
linewid = .5cm
lineht = .5cm
boxwid = 3.5cm

X0: oval "username" fit
arrow
X1: box "GetUser" fit

arrow from X1.ne right color lightblue
oval "Success" fit fill lightblue
arrow from X1.se right color orange
oval "Failure" fit fill orange
....

[source,cs]
....
(User OR Error) GetUser(string username);
....

This sounds trivial, so why isn't this done traditionally?
At least part of that has to do with the fact C-like languages do not make it easy to do this.
You would need to have a return type that can be _either_ the success type _or_ the failure type.
In functional programming languages such a construct _does_ exist and is called a https://en.wikipedia.org/wiki/Tagged_union[Discriminated Union].
But C-like languages, including C#, do not have support for such a type.
Luckily C# has had added lots of language features over the years that make it possible to emulate discriminated unions and use them in a relatively convenient and type-safe way.
We will have a look at one way of implementing explicit failure in C#: a `Result` type with two subtypes, one for the success path and one for the failure path.

### There is still a place for exceptions
Making the failure path part of the function return type does not mean that there are no exceptional situations for which the exception throwing mechanism is a good fit.
To give an extreme example, almost any function can _in theory_ encounter an `OutOfMemoryException` while doing an allocation.
Or any function could _in theory_ contain a bug causing a `NullReferenceException` to be thrown.
But this does not mean that we should write every function with that in mind, and have it be part of the normal failure path.
These cases are really exceptions which are *unexpected*, and should not happen.
There is often no proper way to handle them other than to cancel the whole "operation" and present the user with an appropriate error, indicating that something went completely sideways.

A good way for deciding whether to propagate a failure by throwing an exception is by asking the following question.
_Would the exeption be handled with no error-specific logic and should it cause the entire operation that is being done to be aborted_?
If the answer is yes, then it is probably appropriate to let the failure be handled by throwing an exception and catch it up the callchain at the "edge of the operation".

What the scope of that "operation" should be is completely context dependent.
For instance, in a web application that could be the http request. 
In other contexts, like a CLI progam, it could be the whole process. 
Again, note that the edges of the code that constitutes an "operation" should have appropriate try/catch clauses.

Tldr, exceptions should not be dealt with on a function level but rather on an "operation" level, and they are really *exceptional*.
