= Railroad Oriented Programming in C#: Part 4

## Subtracks and failure recovery

Railroad Oriented Programming is not limited to having a single straight railroad.
As we compose functions together writing our program, a more complex railroad system will evolve, reflecting our program flow.
It is highly recommended that one does not put too much complex railroad logic in a single function, but it is perfectly possible to construct subtracks within a railroad function.
Let's give an example that demonstrates having a subtrack and performing a failure recovery.

Suppose that now the `SendEmail` function does not return a `string` on failure, but some failure object like an `Exception` instance.

[source,cs]
....
Result<Unit, Exception> SendEmail(EmailMessage email, MailServer server);
....

We could then inspect this failure object and decide how to handle it based on the kind of failure.

[source,cs]
....
/// <returns>Message to be printed on the screen</returns>
string MailMessageToUser(string username, string msg, MailServer server1, MailServer server2) {
  return GetUser(username)
    .OnSuccess(GetEmailAddress)
    .OnSuccess(emailAddress => CreateEmailMessage(emailAddress, msg))
    .OnSuccess(email => SendEmail(email, server1)
      .OnFailure(ex => ex switch {
        ServerNotFoundException => 
          // Attempt server1. We don't need to inspect the second exception,
          // and can directly transform it to an error string using OnFailure.
          SendEmail(email, server2).OnFailure<string>(ex => Result.Fail(ex.Message)),
        _ => Result.Fail(ex.Message)
      })
    )
    .Handle(
      _ => "Email sent",
      error => {
        LogError(error);
        return "Email not sent";
      }
    );
}
....

Here we attempt to defer our email to a second mail server when the first server appears unreachable.
The function `MailMessageToUser` having two mail servers as parameters is a little odd, and probably not how we would want to do it in real life.
But it demonstrates having subtracks and failure recovery very well in the context of our email example.

[pikchr]
....
include::rop.pikchr[]

startResult("GetUser","User","string")
onSuccess("GetEmailAddress","string")
onSuccess("CreateEmailMessage","MailMessage")
newline

S0: arrow color lightblue
B1: box "SendEmail" fit
line right linewid color orange behind B1
EX: oval "Exception" fit
arrow right linewid color orange behind B1
B2: box "SendEmail2" fit
line right linewid*2 color lightblue behind B2
oval "Unit" fit
E: line right color lightblue behind last oval

line behind B1 from B1.e right linerad then up then right until even with B2.e then right linerad*2 then down then right color lightblue
line behind EX from EX.e right linerad then down then right color orange

move from S0.start down lineht
line right until even with E.end color orange

line from B2.e right linerad then down then right color orange behind B2

move to E.end

handle("Handle","string")
....
